### ISSUE TITLE
--with-passenger uses rake apache

### ISSUE THREAD

**Issue by ivdma** [Homebrew/homebrew-nginx#213]
On a fresh installation of macOS `brew install nginx --with-passenger` uses apache headers. I am using golden master of macOS Sierra and I am aware that brew does not officially support it yet. But this could also affect the release version.

```bash
➜ brew install nginx --with-passenger
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for nginx: passenger
==> Installing nginx dependency: passenger
==> Using the sandbox
==> Downloading https://s3.amazonaws.com/phusion-passenger/releases/passenger-5.0.30.tar.gz
Already downloaded: /Users/ivan/Library/Caches/Homebrew/passenger-5.0.30.tar.gz
==> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/rake apache2
Last 15 lines from /Users/ivan/Library/Logs/Homebrew/passenger/01.rake:
clang -o buildout/apache2/mod_passenger.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -fPIC -I/usr/include/apache2 -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -g -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -c src/apache2_module/mod_passenger.c
In file included from src/apache2_module/mod_passenger.c:26:
In file included from /usr/include/apache2/httpd.h:44:
In file included from /usr/include/apache2/ap_config.h:25:
/usr/include/apache2/ap_hooks.h:39:10: fatal error: 'apr.h' file not found
#include "apr.h"
         ^
1 error generated.
rake aborted!
Command failed with status (1): [clang -o buildout/apache2/mod_passenger.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -fPIC -I/usr/include/apache2 -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -g -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -c src/apache2_module/mod_passenger.c]
/private/tmp/passenger-20160916-4735-9kc7k2/passenger-5.0.30/build/support/cplusplus.rb:52:in `run_compiler'
/private/tmp/passenger-20160916-4735-9kc7k2/passenger-5.0.30/build/support/cplusplus.rb:96:in `compile_c'
/private/tmp/passenger-20160916-4735-9kc7k2/passenger-5.0.30/build/support/cplusplus.rb:153:in `block in define_c_object_compilation_task'
Tasks: TOP => apache2 => buildout/apache2/mod_passenger.so => buildout/apache2/mod_passenger.o
(See full trace by running task with --trace)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by denji** [comment]
Usually system libraries and header files apach2 with the `xcode-select --install`

**Comment by ivdma** [comment]
I think Apple has removed apache2 headers from macOS Sierra and (I assume) from recent command line tools too. I have Command Line Tools installed (brew did this for me).

**Comment by ivdma** [comment]
Anyways: I see no reason to use apache headers when I install nginx --with-passenger.

**Comment by denji** [comment]
We use passenger of the basic supplies that I think should write in the main repository https://github.com/Homebrew/homebrew-core/issues/new [(`passenger.rb`)](https://github.com/Homebrew/homebrew-core/blob/master/Formula/passenger.rb)

**Comment by denji** [comment]
```bash
brew up && brew upgrade
brew reinstall passenger --without-apache2-module # macOS Sierra
brew install nginx --with-passenger
```

**Comment by denji** [comment]
Thanks, I think issue can be closed and opened https://github.com/Homebrew/homebrew-core/issues/new.
